on:
   push:
     branches:
       - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: lholmquist/release-please-action@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: testing-release-automation
